Application:
  repository_type: database
  host: 127.0.0.1
  port: 8000
  debug: true

DataBase:
  db_type: mysql
  host: 127.0.0.1
  port: 3306
  user: root
  password: password
  database: database

SMTP:
  host: localhost
  port: 587
  tls: true
  password: "qwerty123456"
  email_from: user12381@gmail.com
